import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class IconHelper {
  static const IconData homeIcon = Icons.home;
  static const IconData homeIconPassive = Icons.home_outlined;
  static const IconData searchIcon = CupertinoIcons.search_circle_fill;
  static const IconData searchPassiveIcon = CupertinoIcons.search_circle;
  static const IconData libraryIcon = Icons.insert_drive_file_rounded;
  static const IconData libraryPassiveIcon = Icons.insert_drive_file_outlined;
  static const IconData notificationIcon = CupertinoIcons.bell;
  static const IconData timeIcon = CupertinoIcons.time;
  static const IconData settingIcon = Icons.settings_outlined;
  static const IconData pauseIcon = CupertinoIcons.pause_fill;
  static const IconData playIcon = CupertinoIcons.play_arrow_solid;
  static const IconData gridIcon = CupertinoIcons.gift_alt_fill;
  static const IconData listIcon = Icons.menu_sharp;
  static const IconData likeIcon = CupertinoIcons.heart;
  static const IconData like2Icon = CupertinoIcons.heart_fill;
  static const IconData addPlaylistIcon = CupertinoIcons.music_note_2;
  static const IconData addQueueIcon = CupertinoIcons.list_bullet;
  static const IconData showAlbumIcon = CupertinoIcons.calendar_circle;
  static const IconData showArtistIcon = CupertinoIcons.person;
  static const IconData shareIcon = Icons.share;
  static const IconData shareOutlinedIcon = Icons.share_outlined;
  static const IconData goSongRadioIcon = Icons.wifi_tethering;
  static const IconData showContributersIcon = CupertinoIcons.person_add;
  static const IconData arrowLeftIcon = CupertinoIcons.arrow_left;
  static const IconData addIcon = CupertinoIcons.add;
  static const IconData menuIcon = CupertinoIcons.ellipsis_vertical;
  static const IconData menu2Icon = Icons.calendar_view_day_outlined;
  static const IconData downloadIcon = CupertinoIcons.arrow_down_circle_fill;
  static const IconData search2Icon = CupertinoIcons.search;
  static const IconData play2Icon = CupertinoIcons.play_circle_fill;
  static const IconData shuffleIcon = CupertinoIcons.shuffle;
  static const IconData deviceIcon = Icons.computer;
  static const IconData backwardIcon = CupertinoIcons.backward_end;
  static const IconData pinIcon = CupertinoIcons.map_pin;
  static const IconData addCircleIcon = CupertinoIcons.add_circled;
  static const IconData forwardIcon = CupertinoIcons.forward_end;
  static const IconData againIcon = CupertinoIcons.refresh;
  static const IconData fullscreenIcon = CupertinoIcons.fullscreen;
  static const IconData repeatIcon = CupertinoIcons.repeat;
  static const IconData queueIcon = CupertinoIcons.increase_indent;
  static const IconData infoIcon = CupertinoIcons.info;
  static const IconData rightArrowIcon = CupertinoIcons.right_chevron;
  static const IconData upDownArrowIcon = CupertinoIcons.arrow_up_arrow_down;
  static const IconData closeIcon = Icons.close;
  static const IconData checkMarkIcon = CupertinoIcons.check_mark;
  static const IconData arrowDownIcon = Icons.keyboard_arrow_down;
}
